site_name: My Docs
site_url: https://example.com
theme:

  font:
    text: Merriweather Sans
    code: Red Hat Mono

  name: material

  icon:
    logo: fontawesome/solid/d

  favicon: fontawesome/solid/d

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg